version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout
      - run:
          name: Run build with tests
          command: ./gradlew build
      - run:
          name: Save test results
          command: |
                mkdir -p tests/junit
                find build/test-results -name  "*.xml" -exec cp {} tests/junit/ \;
                if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
                bash <(curl -s https://codecov.io/bash)
          when: always
      - store_test_results:
          path: tests
      - store_artifacts:
          path: build/libs
